### ISSUE TITLE
Enable GitHub actions in repo

### ISSUE THREAD

**Issue by mironiasty** [delekta/PokemonMobileApp#5]
Enable simple GitHub actions in repo, to check for TS and Eslint rules for each PR.

For TS this could be done by creating `.github/workflows/check.yml` file:

```yml
name: TypeScript

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run typescript
      run: yarn tsc
```

For eslint - you would have to add comment to run eslint.
